name: twinleafMGMT
favicon: null
layout_spectrum: 0.90423
typography_spectrum: 0.75244
title: twinleafMGMT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#afed90'
    - '#4a4c49'
    - '#80bf80'
    - '#00ff00'
    - '#000000'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.4375
  rhythmicContrast: 0.8633479229174554
purpose: []
