name: twinleafMGMT
favicon: null
layout_spectrum: 0.8948286992963403
typography_spectrum: 0.7179281760472804
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.22679948806762695
  lightness: 0.38319614878855646
  saturation: 0.9166867358144373
  rhythmicContrast: 0.8633479229174554
purpose: []
